import { create } from 'zustand';
import { supabase } from '../services/supabase';
import type { LessonPlan } from '../types/lesson';

interface LessonStore {
    plans: LessonPlan[];
    isLoading: boolean;
    fetchPlans: () => Promise<void>;
    addPlan: (plan: LessonPlan) => Promise<void>;
    removePlan: (id: string) => Promise<void>;
    getPlan: (id: string) => LessonPlan | undefined;
}

export const useLessonStore = create<LessonStore>((set, get) => ({
    plans: [],
    isLoading: false,

    fetchPlans: async () => {
        set({ isLoading: true });
        try {
            const { data, error } = await supabase
                .from('lesson_plans')
                .select('*')
                .order('created_at', { ascending: false });

            if (error) throw error;

            const formattedPlans: LessonPlan[] = (data || []).map(item => ({
                id: item.id,
                title: item.title,
                discipline: item.discipline,
                grade: item.grade,
                theme: item.theme,
                duration: item.duration,
                context: item.context,
                createdAt: item.created_at,
                content: item.content
            }));

            set({ plans: formattedPlans });
        } catch (error) {
            console.error('Error fetching plans:', error);
        } finally {
            set({ isLoading: false });
        }
    },

    addPlan: async (plan) => {
        // Optimistic update
        set((state) => ({ plans: [plan, ...state.plans] }));

        try {
            const { error } = await supabase
                .from('lesson_plans')
                .insert({
                    id: plan.id, // Use the ID generated by the frontend or let DB generate it? 
                    // Usually better to let DB generate, but if we have it... 
                    // The AI generator creates a UUID. Let's use it or upsert.
                    // Actually, let's just insert what we have, but map to snake_case
                    title: plan.title,
                    discipline: plan.discipline,
                    grade: plan.grade,
                    theme: plan.theme,
                    duration: plan.duration,
                    context: plan.context,
                    content: plan.content,
                    created_at: plan.createdAt
                });

            if (error) throw error;
        } catch (error) {
            console.error('Error adding plan:', error);
            // Revert optimistic update if needed, but for MVP we just log
        }
    },

    removePlan: async (id) => {
        // Optimistic update
        set((state) => ({ plans: state.plans.filter((p) => p.id !== id) }));

        try {
            const { error } = await supabase
                .from('lesson_plans')
                .delete()
                .eq('id', id);

            if (error) throw error;
        } catch (error) {
            console.error('Error removing plan:', error);
        }
    },

    getPlan: (id) => get().plans.find((p) => p.id === id),
}));
