export interface LessonPlan {
    id: string;
    title: string; // Generated or User defined
    discipline: string;
    grade: string;
    theme: string;
    duration: string;
    context: string;
    createdAt: string;
    headerColor?: string;

    // Content generated by AI
    content: {
        foundation: string; // Fundamentação
        generalObjective: string; // Objetivo Geral
        specificObjectives: string[]; // Objetivos Específicos
        content: string[]; // Conteúdo
        methodology: string; // Metodologia
        resources: string[]; // Recursos Didáticos
        evaluation: string; // Avaliação
        bnccSkills: string[]; // Habilidades BNCC
        adaptations: string; // Adaptações (educação inclusiva)
        homework: string; // Atividades de Casa
    } | null;
}

export type LessonPlanFormData = Pick<LessonPlan, 'discipline' | 'grade' | 'theme' | 'duration' | 'context'>;
